### PR TITLE
To Master

### PR DESCRIPTION
**Pull request by KillerX**
Are we ok to go to STA and PROD or do we have some known issues/risks?

### CODE REVIEW

**Comment by KillerX** [comment]
Are we ok to go to STA and PROD or do we have some known issues/risks?

**Comment by fredrikved** [comment]
Idtokens from the app might break as I haven't tested with those, but the dev environment works as expected.

**Review by fredrikved — APPROVED** [review]

**Comment by andreasgan** [comment]
idtokens should work before merging??

**Comment by andreasgan** [comment]
@fredrikved

**Comment by fredrikved** [comment]
Id-tokens work fine.

**Comment by KillerX** [comment]
Setting this on hold until I can fix an ingest issue in PROD.

**Pull request merged**
